appName: emailservice
appImage: bigchuch/google-microservices
appVersion: v1
appReplicas: 1
containerPort: 8080
containerEnvVars:
- name: PORT
  value: "8080"
 
nameSpace: microservices

servicePort: 5000
serviceType: ClusterIP