helm install -f values/redis-cart.yaml redis charts/redis
helm install -f values/adservice.yaml adservice charts/microservices
helm install -f values/cartservice.yaml cartservice charts/microservices
helm install -f values/checkoutservice.yaml checkoutservice charts/microservices
helm install -f values/currencyservice.yaml currencyservice charts/microservices
helm install -f values/email-service-values.yaml emailservice charts/microservices
helm install -f values/frontend.yaml frontend charts/microservices
helm install -f values/paymentservice.yaml paymentservice charts/microservices
helm install -f values/productcatalogservice.yaml productcatalogservice charts/microservices
helm install -f values/recommendationservice-value.yaml recommendationservice charts/microservices
helm install -f values/shippingservice.yaml shippingservice charts/microservices
