# Deployment configurations for all microservices
# Extracted from config.yaml

# Email Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
  namespace: microservices
  labels:
    app: emailservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      containers:
        - name: service
          image: bigchuch/google-microservices:emailservice-v1
          ports: 
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"

---
# Recommendation Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationservice
  namespace: microservices
  labels:
    app: recommendationservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendationservice
  template:
    metadata:
      labels:
        app: recommendationservice
    spec:
      containers:
        - name: service
          image: bigchuch/google-microservices:recommendationservice-v1
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080" 
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "productcatalogservice:3550"

---
# Product Catalog Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
  namespace: microservices
  labels:
    app: productcatalogservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productcatalogservice
  template:
    metadata:
      labels:
        app: productcatalogservice
    spec:
      containers:
        - name: service
          image: bigchuch/google-microservices:productcatalogservice-v1
          ports:
            - containerPort: 3550
          env:
            - name: PORT
              value: "3550"

---
# Payment Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  namespace: microservices
  labels:
    app: paymentservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
        - name: service
          image: bigchuch/google-microservices:paymentservice-v1
          ports: 
            - containerPort: 50051
          env:
            - name: PORT
              value: "50051"
            - name: DISABLE_PROFILER
              value: "1"

---
# Currency Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
  namespace: microservices
  labels:
    app: currencyservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currencyservice
  template:
    metadata:
      labels:
        app: currencyservice
    spec:
      containers:
        - name: service
          image: bigchuch/google-microservices:currencyservice-v1
          ports:
            - containerPort: 7000
          env:
            - name: PORT
              value: "7000"
            - name: DISABLE_PROFILER
              value: "1"

---
# Shipping Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
  namespace: microservices
  labels:
    app: shippingservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      containers:
        - name: service
          image: bigchuch/google-microservices:shippingservice-v1
          ports:
            - containerPort: 50051

---
# Ad Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
  namespace: microservices
  labels:
    app: adservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      containers:
        - name: service
          image: bigchuch/google-microservices:adservice-v1
          ports:
            - containerPort: 9555
          env:
            - name: PORT
              value: "9555"

---
# Cart Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  namespace: microservices
  labels:
    app: cartservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      containers:
        - name: service
          image: bigchuch/google-microservices:cartservice-v1
          ports:
            - containerPort: 7070
          env:
            - name: PORT
              value: "7070"
            - name: REDIS_ADDR
              value: "redis-cart:6379"

---
# Redis Cart Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cart
  namespace: microservices
  labels:
    app: redis-cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-cart
  template:
    metadata:
      labels:
        app: redis-cart
    spec:
      containers:
        - name: redis
          image: redis:alpine
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          emptyDir: {}

---
# Checkout Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
  namespace: microservices
  labels:
    app: checkoutservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
    spec:
      containers:
        - name: service
          image: bigchuch/google-microservices:checkoutservice-v1
          ports:
            - containerPort: 5050
          env:
            - name: PORT
              value: "5050"
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "productcatalogservice:3550"
            - name: CART_SERVICE_ADDR
              value: "cartservice:7070"
            - name: CURRENCY_SERVICE_ADDR
              value: "currencyservice:7000"
            - name: SHIPPING_SERVICE_ADDR
              value: "shippingservice:50051"
            - name: EMAIL_SERVICE_ADDR
              value: "emailservice:5000"
            - name: PAYMENT_SERVICE_ADDR
              value: "paymentservice:50051"

---
# Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: microservices
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: service
          image: bigchuch/google-microservices:frontend-v1
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "productcatalogservice:3550"
            - name: CART_SERVICE_ADDR
              value: "cartservice:7070"
            - name: CURRENCY_SERVICE_ADDR
              value: "currencyservice:7000"
            - name: SHIPPING_SERVICE_ADDR
              value: "shippingservice:50051"
            - name: CHECKOUT_SERVICE_ADDR
              value: "checkoutservice:5050"
            - name: RECOMMENDATION_SERVICE_ADDR
              value: "recommendationservice:8080"
            - name: AD_SERVICE_ADDR
              value: "adservice:9555"
            - name: SHOPPING_ASSISTANT_SERVICE_ADDR
              value: "shoppingassistantservice:8080"