# Service configurations for all microservices
# Extracted from config.yaml

# Email Service
apiVersion: v1
kind: Service
metadata:
  name: emailservice
  namespace: microservices
  labels:
    app: emailservice
spec:
  type: ClusterIP
  selector:
    app: emailservice
  ports:
    - name: grpc
      port: 5000
      targetPort: 8080

---
# Recommendation Service
apiVersion: v1
kind: Service
metadata:
  name: recommendationservice
  namespace: microservices
  labels:
    app: recommendationservice
spec:
  type: ClusterIP
  selector:
    app: recommendationservice
  ports:
    - name: grpc
      port: 8080
      targetPort: 8080

---
# Product Catalog Service
apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
  namespace: microservices
  labels:
    app: productcatalogservice
spec:
  type: ClusterIP
  selector:
    app: productcatalogservice
  ports:
    - name: grpc
      port: 3550
      targetPort: 3550

---
# Payment Service
apiVersion: v1
kind: Service
metadata:
  name: paymentservice
  namespace: microservices
  labels:
    app: paymentservice
spec:
  type: ClusterIP
  selector:
    app: paymentservice
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051

---
# Currency Service
apiVersion: v1
kind: Service
metadata:
  name: currencyservice
  namespace: microservices
  labels:
    app: currencyservice
spec:
  type: ClusterIP
  selector:
    app: currencyservice
  ports:
    - name: grpc
      port: 7000
      targetPort: 7000

---
# Shipping Service
apiVersion: v1
kind: Service
metadata:
  name: shippingservice
  namespace: microservices
  labels:
    app: shippingservice
spec:
  type: ClusterIP
  selector:
    app: shippingservice
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051

---
# Ad Service
apiVersion: v1
kind: Service
metadata:
  name: adservice
  namespace: microservices
  labels:
    app: adservice
spec:
  type: ClusterIP
  selector:
    app: adservice
  ports:
    - name: grpc
      port: 9555
      targetPort: 9555

---
# Cart Service
apiVersion: v1
kind: Service
metadata:
  name: cartservice
  namespace: microservices
  labels:
    app: cartservice
spec:
  type: ClusterIP
  selector:
    app: cartservice
  ports:
    - name: grpc
      port: 7070
      targetPort: 7070

---
# Redis Cart Service
apiVersion: v1
kind: Service
metadata:
  name: redis-cart
  namespace: microservices
  labels:
    app: redis-cart
spec:
  type: ClusterIP
  selector:
    app: redis-cart
  ports:
    - name: redis
      port: 6379
      targetPort: 6379

---
# Checkout Service
apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
  namespace: microservices
  labels:
    app: checkoutservice
spec:
  type: ClusterIP
  selector:
    app: checkoutservice
  ports:
    - name: grpc
      port: 5050
      targetPort: 5050

---
# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: microservices
  labels:
    app: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30007
  type: NodePort  
