apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName}}
  namespace: {{ .Values.nameSpace }}
  labels:
    app: {{ .Values.appName}}
spec:
  type: {{ .Values.serviceType}}
  selector:
    app: {{ .Values.appName}}
  ports:
    - protocol: TCP
      port: {{ .Values.servicePort}}
      targetPort: {{ .Values.containerPort}}
      {{- if and (eq .Values.serviceType "NodePort") .Values.nodePort }}
      nodePort: {{ .Values.nodePort }}
      {{- end }}
